version: "3.8"

services:
    
    webserver:
        container_name: new_youtube_webserver
        build:
            context: .docker/webserver
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - .docker/webserver/000-default.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - "8081:80"